---
title: Functional specificity and neural integration in the aesthetic appreciation
  of artworks with implied motion
author: "Ionela Bara, Kohinoor M. Darda, A. Solomon Kurz, & Richard Ramsey"
date: "2021-09-17"
output:
  html_document:
    df_print: paged
image:
  caption: ''
  focal_point: ''
  preview_only: no
publishDate: "2021-09-17"
tags:
- aesthetic judgement
- body shape
- fMRI
- motion perception
- reward circuit
links:
- icon: "file-pdf"
  icon_pack: fa
  name: PDF
  url: pdf/Bara et al (2021) Functional specificity and neural integration in the
    aesthetic appreciation of artworks with implied motion.pdf
- icon: osf
  icon_pack: ai
  name: OSF
  url: https://osf.io/x5d2g/
- icon: psyarxiv
  icon_pack: ai
  name: PsyArXiv
  url: https://psyarxiv.com/qm3ga/
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://doi.org/10.1111/ejn.15479
featured: no
---

## Abstract

Although there is growing interest in the neural foundations of aesthetic experience, it remains unclear how particular mental subsystems (e.g. perceptual, affective and cognitive) are involved in different types of aesthetic judgements. Here, we use fMRI to investigate the involvement of different neural networks during aesthetic judgements of visual artworks with implied motion cues. First, a behavioural experiment $(N = 45)$ confirmed a preference for paintings with implied motion over static cues. Subsequently, in a preregistered fMRI experiment $(N = 27)$, participants made aesthetic and motion judgements towards paintings representing human bodies in dynamic and static postures. Using functional region-of-interest and Bayesian multilevel modelling approaches, we provide no compelling evidence for unique sensitivity within or between neural systems associated with body perception, motion and affective processing during the aesthetic evaluation of paintings with implied motion. However, we show suggestive evidence that motion and body-selective systems may integrate signals via functional connections with a separate neural network in dorsal parietal cortex, which may act as a relay or integration site. Our findings clarify the roles of basic visual and affective brain circuitry in evaluating a central aesthetic feature—implied motion—while also pointing towards promising future research directions, which involve modelling aesthetic preferences as hierarchical interplay between visual and affective circuits and integration processes in frontoparietal cortex.

```{}
@article{baraFunctionalSpecificity2021,
  title = {Functional specificity and neural integration in the aesthetic appreciation of artworks with implied motion},
  author = {Ionela Bara and Kohinoor Monish Darda and A. Solomon Kurz and Richard Ramsey},
  journal = {European Journal of Neuroscience},
  year = 2021,
  volume = 54,
  issue = 9,
  page = 7231–7259,
  doi = {https://doi.org/10.1111/ejn.15479}
}
```



