---
title: "Courses"
author: "A. Solomon Kurz"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
# layout: single
layout: wide-body # standard or wide-body
show_title_as_headline: true
---

## 2022

### Fall semester

#### *Statistical Analysis* (PA 652)

**For**: [The Chicago School of Professional Psychology, Los Angeles](https://www.thechicagoschool.edu/learn/los-angeles/?utm_campus=105)

**Where**: Online

**Goal**: This course is designed to introduce the generalized linear mixed model (GLMM) to doctoral students in behavior analysis. We start the semester with simple regression via ordinary least squares, introduce the generalized linear model with maximum likelihood by mid semester, and end the semester with conditional longitudinal models via the full GLMM. Along the way, students learn about open science principles and how to program in the R computing language.

**Website**: You can find the syllabus and other supporting materials on the course website at https://osf.io/zdp3s/

### Spring semester

#### *Research in Psychology and Education* (PA 650)

**For**: [The Chicago School of Professional Psychology, Los Angeles](https://www.thechicagoschool.edu/learn/los-angeles/?utm_campus=105)

**Where**: Online

**Goal**: The name and number for this course are a little misleading. This course is an extension of the introductory course, *Statistical Analysis* (PA 652). Herein the students learn about research design through the lens of their newly-acquired skills at the GLMM. We cover a broad range of research paradigms, such as between-person designs (i.e., the pre/post randomized controlled trial), within-person design (i.e., the multiple-baseline ABAB reversal), and mixed designs (i.e., mixed factorial reaction-time paradigms). Specialty topics include simulation-based power analysis and multilevel model effect sizes. All programming is done in the R computing language.

**Website**: You can find the syllabus and other supporting materials on the course website at https://osf.io/wcm6r/

## 2021

### Fall semester

#### *Statistical Analysis* (PA 652)

**For**: [The Chicago School of Professional Psychology, Los Angeles](https://www.thechicagoschool.edu/learn/los-angeles/?utm_campus=105)

**Where**: Online

**Goal**: This course is designed to introduce the generalized linear mixed model (GLMM) to doctoral students in behavior analysis. We start the semester with simple regression via ordinary least squares, introduce the generalized linear model with maximum likelihood by mid semester, and end the semester with conditional longitudinal models via the full GLMM. Along the way, students learn about open science principles and how to program in the R computing language. 

**Website**: You can find the syllabus and other supporting materials on the course website at https://osf.io/3g8vf/

## 2018 and earlier

**For**: [The University of Mississippi](https://psychology.olemiss.edu/)

**Where**: The main campus in University, MS

**What**: During my graduate training, I taught:

* 5 semesters of *General Psychology* (Psy 201) and 
* 5 semesters of *Meditation in Daily Life* (Psy 405).

Both courses were aimed at an undergraduate audience. Sadly, this was long before I was in the practice of saving course materials in online repositories. So it goes...

